const keysLayout = [
    [
        {
            value1: '`',
            value2: 'ё',
            alt1: '~',
            alt2: null,
            code: 'Backquote',
        },
        {
            value1: '1',
            value2: '1',
            alt1: '!',
            alt2: '!',
            code: 'Digit1',
        },
        {
            value1: '2',
            value2: '2',
            alt1: '@',
            alt2: '"',
            code: 'Digit2',
        },
        {
            value1: '3',
            value2: '3',
            alt1: '#',
            alt2: '№',
            code: 'Digit3',
        },
        {
            value1: '4',
            value2: '4',
            alt1: '$',
            alt2: ';',
            code: 'Digit4',
        },
        {
            value1: '5',
            value2: '5',
            alt1: '%',
            alt2: '%',
            code: 'Digit5',
        },
        {
            value1: '6',
            value2: '6',
            alt1: '^',
            alt2: ':',
            code: 'Digit6',
        },
        {
            value1: '7',
            value2: '7',
            alt1: '&',
            alt2: '?',
            code: 'Digit7',
        },
        {
            value1: '8',
            value2: '8',
            alt1: '*',
            alt2: '*',
            code: 'Digit8',
        },
        {
            value1: '9',
            value2: '9',
            alt1: '(',
            alt2: '(',
            code: 'Digit9',
        },
        {
            value1: '0',
            value2: '0',
            alt1: ')',
            alt2: ')',
            code: 'Digit0',
        },
        {
            value1: '-',
            value2: '-',
            alt1: '_',
            alt2: '_',
            code: 'Minus',
        },
        {
            value1: '=',
            value2: '=',
            alt1: '+',
            alt2: '+',
            code: 'Equal',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'Backspace',
        },
    ],
    [
        {
            value1: '    ',
            value2: '    ',
            alt1: null,
            alt2: null,
            code: 'Tab',
        },
        {
            value1: 'q',
            value2: 'й',
            alt1: 'Q',
            alt2: 'Й',
            code: 'KeyQ',
        },
        {
            value1: 'w',
            value2: 'ц',
            alt1: 'W',
            alt2: 'Ц',
            code: 'KeyW',
        },
        {
            value1: 'e',
            value2: 'у',
            alt1: 'E',
            alt2: 'У',
            code: 'KeyE',
        },
        {
            value1: 'r',
            value2: 'к',
            alt1: 'R',
            alt2: 'К',
            code: 'KeyR',
        },
        {
            value1: 't',
            value2: 'е',
            alt1: 'T',
            alt2: 'Е',
            code: 'KeyT',
        },
        {
            value1: 'y',
            value2: 'н',
            alt1: 'Y',
            alt2: 'Н',
            code: 'KeyY',
        },
        {
            value1: 'u',
            value2: 'г',
            alt1: 'U',
            alt2: 'Г',
            code: 'KeyU',
        },
        {
            value1: 'i',
            value2: 'ш',
            alt1: 'I',
            alt2: 'Ш',
            code: 'KeyI',
        },
        {
            value1: 'o',
            value2: 'щ',
            alt1: 'O',
            alt2: 'Щ',
            code: 'KeyO',
        },
        {
            value1: 'p',
            value2: 'з',
            alt1: 'P',
            alt2: 'З',
            code: 'KeyP',
        },
        {
            value1: '[',
            value2: 'х',
            alt1: '{',
            alt2: 'Х',
            code: 'BracketLeft',
        },
        {
            value1: ']',
            value2: 'ъ',
            alt1: '}',
            alt2: 'Ъ',
            code: 'BracketRight',
        },
        {
            value1: '\\',
            value2: '\\',
            alt1: '|',
            alt2: '/',
            code: 'Backslash',
        },
    ],
    [
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'CapsLock',
        },
        {
            value1: 'a',
            value2: 'ф',
            alt1: 'A',
            alt2: 'Ф',
            code: 'KeyA',
        },
        {
            value1: 's',
            value2: 'ы',
            alt1: 'S',
            alt2: 'Ы',
            code: 'KeyS',
        },
        {
            value1: 'd',
            value2: 'в',
            alt1: 'D',
            alt2: 'В',
            code: 'KeyD',
        },
        {
            value1: 'f',
            value2: 'а',
            alt1: 'F',
            alt2: 'А',
            code: 'KeyF',
        },
        {
            value1: 'g',
            value2: 'п',
            alt1: 'G',
            alt2: 'П',
            code: 'KeyG',
        },
        {
            value1: 'h',
            value2: 'р',
            alt1: 'H',
            alt2: 'Р',
            code: 'KeyH',
        },
        {
            value1: 'j',
            value2: 'о',
            alt1: 'J',
            alt2: 'О',
            code: 'KeyJ',
        },
        {
            value1: 'k',
            value2: 'л',
            alt1: 'K',
            alt2: 'Л',
            code: 'KeyK',
        },
        {
            value1: 'l',
            value2: 'д',
            alt1: 'L',
            alt2: 'Д',
            code: 'KeyL',
        },
        {
            value1: ';',
            value2: 'ж',
            alt1: ':',
            alt2: 'Ж',
            code: 'Semicolon',
        },
        {
            value1: "'",
            value2: 'э',
            alt1: '"',
            alt2: 'Э',
            code: 'Quote',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'Enter',
        },
    ],
    [
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ShiftLeft',
        },
        {
            value1: 'z',
            value2: 'я',
            alt1: 'Z',
            alt2: 'Я',
            code: 'KeyZ',
        },
        {
            value1: 'x',
            value2: 'ч',
            alt1: 'X',
            alt2: 'Ч',
            code: 'KeyX',
        },
        {
            value1: 'c',
            value2: 'с',
            alt1: 'C',
            alt2: 'С',
            code: 'KeyC',
        },
        {
            value1: 'v',
            value2: 'м',
            alt1: 'V',
            alt2: 'М',
            code: 'KeyV',
        },
        {
            value1: 'b',
            value2: 'и',
            alt1: 'B',
            alt2: 'И',
            code: 'KeyB',
        },
        {
            value1: 'n',
            value2: 'т',
            alt1: 'N',
            alt2: 'Т',
            code: 'KeyN',
        },
        {
            value1: 'm',
            value2: 'ь',
            alt1: 'M',
            alt2: 'Ь',
            code: 'KeyM',
        },
        {
            value1: ',',
            value2: 'б',
            alt1: '<',
            alt2: 'Б',
            code: 'Comma',
        },
        {
            value1: '.',
            value2: 'ю',
            alt1: '>',
            alt2: 'Ю',
            code: 'Period',
        },
        {
            value1: '/',
            value2: '.',
            alt1: '?',
            alt2: ',',
            code: 'Slash',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ArrowUp',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ShiftRight',
        },
    ],
    [
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ControlLeft',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'MetaLeft',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'AltLeft',
        },
        {
            value1: ' ',
            value2: ' ',
            alt1: null,
            alt2: null,
            code: 'Space',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'AltRight',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ControlLeft',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ArrowLeft',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ArrowDown',
        },
        {
            value1: '',
            value2: '',
            alt1: null,
            alt2: null,
            code: 'ArrowRight',
        },
    ],
];